apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-secret
  name: my-secret
spec:
  volumes:
  - name: auth
    secret:
      secretName: my-auth
  containers:
  - image: prestashop:1.7
    name: my-secret
    resources: {}
    volumeMounts:
    - name: auth
      mountPath: "/etc/auth"
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}